### ISSUE TITLE
Meten

### ISSUE THREAD

**Issue by samuvack** [samuvack/Search#11]
De functie meten, zou nog moeten toegevoegd worden. Dit dient wel een nauwkeurige meetfunctie te zijn.

**Comment by VandorpeDavid** [comment]
Nauwkeurigheid kan een probleem worden aangezien er sowieso al een fout zit op de plaats waar de gebruiker klikt.

**Comment by samuvack** [comment]
Geen enkel probleem. Als er al een schatting van de afstand kan gedaan worden, is dat ook goed :)
