### ISSUE TITLE
Online plaatsen

### ISSUE THREAD

**Issue by samuvack** [samuvack/Search#15]
Aangezien de nieuwe Server nog niet aangemaakt is, maar de site toch online zou moeten komen..
Zou de web applicatie online moeten komen, net zoals het bij Berdien werd gedaan.

Veel succes!
En dikke merci voor alles tot nu toe ;)

**Comment by VandorpeDavid** [comment]
Mogen wij dit op de cartogis server plaatsen?

**Comment by samuvack** [comment]
​Dag David

Ik zit vandaag jammer genoeg ziek thuis.

De webapp mag inderdaad op de cartogis server geplaatst worden. Dat zou super zijn,
mocht dat nog kunnen lukken!

Veel succes!

En heel erg bedankt voor alles.

Mvg,
Samuel

**Comment by VandorpeDavid** [comment]
Deployed: http://cartogis.ugent.be/Search/ .
