### ISSUE TITLE
Toekomstig uitzicht

### ISSUE THREAD

**Issue by samuvack** [samuvack/Search#20]
De app zou er zo moeten uitzien:
[http://cartogis.ugent.be/Search/web/Toekomstige%20app.png](http://cartogis.ugent.be/Search/web/Toekomstige%20app.png)

De layerbox, infobox, legende en timeline zou moeten vast staan, zoals op de print screen.

**Comment by VandorpeDavid** [comment]
Dus de layerbox naar rechts, en de timeline van #16 onderaan. Mis ik nog iets?

Alle boxen permanent open laten staan wordt problematisch bij kleine(re) schermen.

**Comment by VandorpeDavid** [comment]
Zie eff39e1a .
Als de layersbox naar rechts het enige was, gelieve dit dan te sluiten. @samuvack 

Timeline hoort bij #16

**Comment by samuvack** [comment]
Neen, het moet allemaal openblijven staan :) Dus, als je op de website komt,
moet de legende, het infomenu en het layermenu open blijven staan (behalve bij gsm/tablet)
