### ISSUE TITLE
Registreren

### ISSUE THREAD

**Issue by samuvack** [samuvack/Search#23]
Ik krijg deze error:

Catchable fatal error: Argument 1 passed to MyApp\User\Mailer::sendConfirmationMessage() must be an instance of MyApp\User\User, instance of MyApp\Entities\User given, called in /var/www/Search/admin/app/controllers/UserController.php on line 111 and defined in /var/www/Search/admin/src/user/Mailer.php on line 144

**Comment by VandorpeDavid** [comment]
Fixed
