### ISSUE TITLE
Fit to extent

### ISSUE THREAD

**Issue by samuvack** [samuvack/Search#7]
Maak meerdere zoom boxes.

In het SeArch project zijn er verschillende zones interessant. In 'Zone A' wordt er bijvoorbeeld een volledig onderzoek uitgevoerd. Er dient dus een 'Zone A' fit to extent toegevoegd te worden.

Maak zo'n 6 'zoom to extent' knoppen aan.

**Comment by VandorpeDavid** [comment]
Heb je coordinaten+namen van deze zones?

**Comment by samuvack** [comment]
Alles in EPSG 31370

Zone A:
43005, 21105
43478, 211529

Zone B: 
42943, 211007
43479, 211510

Zone C:
42451, 210652
42934, 211155

Zone D:
42174, 210463
42679, 210953

Zone E:
41893, 210291
42389, 210792

**Comment by samuvack** [comment]
Zone A: 
315888, 6656592
316710, 6657414

**Comment by samuvack** [comment]
Alles in EPSG 3857

Zone A: 
315888, 6656592
316710, 6657414

Zone B:
315492, 6656313
316250, 6657097

Zone C:
315047, 6655992
315824, 6656799

Zone D: 
314606, 6655702
315386, 6656501

Zone E:
314157, 6655415
314975, 6656192
